name: 'Valplugin'
version: '1.1.1'
main: 'com.gmail.fahiba228.untitled.Main'
author: 'VALIK3001'
api-version: 1.18

commands:
  cords:
    description: "Показывает координаты выбранного игрока"
    permission: valplugin.cords #право
    usage: '/cords [player]'
  warning:
    description: "Показывает обЪявление по центру экрана всем игрокам"
    permission: valplugin.warning
    usage: '/warning [message]'
  note:
    description: "Создает запись"
    permission: valplugin.notes
    usage: '/note [text]'
  shownote:
    description: "Показывает записи"
    permission: valplugin.notes
    usage: '/<command>'
  delnote:
    description: "Удаляет определенную заметку"
    permission: valplugin.notes
    usage: '/<command> [number]'
  killcords_switch:
    description: "reloading plugin"
    permission: valplugin.switch
    usage: "/reload"

permissions: #права
  valplugin.cords:
    description: ''
    default: 'op'
  valplugin.warning:
    description: ''
    default: 'op'
  valplugin.notes:
    description: 'notes access'
    default: 'true'
  valplugin.switch:
    description: "switch variables acces"
    default: 'op'